name: send_commit
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Run_action_py:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ” your repository is ${{ github.repository }}." 
      - run: echo "ğŸ” your@@@ repository is ${{ github.ref }}." 
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: python
        run: |
          python3 .github/action.py 211.37.174.239 9090 "${{ github.event.head_commit.message }}"
      - run: echo "ğŸ‰ sending your commit msg to ffgc server!"
      - run: echo "ğŸ This job's status is ${{ job.status }}."

